### ISSUE TITLE
Don't store ft_sequence number in header as it gets overwritten anyway

### ISSUE THREAD

**Issue by guihomework** [kuka-isir/rtt_ati_sensor#2]
Code here https://github.com/kuka-isir/rtt_ati_sensor/blob/master/src/rtt_ft_sensor.cpp#L83 suggests the sequence number would contain the ft_sequence but it actually gets overwritten as stated here
http://answers.ros.org/question/55126/why-does-ros-overwrite-my-sequence-number/

So might be changed to not mislead debugging

**Comment by ahoarau** [comment]
Same as https://github.com/kuka-isir/ati_sensor/issues/9

**Comment by guihomework** [comment]
Adding the real point that was posing problem (specify the commit) https://github.com/kuka-isir/rtt_ati_sensor/blob/d4b12b9668deb37ca845b165111eeb382d58e6f2/src/rtt_ft_sensor.cpp#L83

**Comment by ahoarau** [comment]
@guihomework I lost track on this. Is it fixed ?

**Comment by guihomework** [comment]
I think its your decision if you want to remove that line because the data gets overwritten anyway. does not harm is just non useful after I noticed the data gets erased.

**Comment by ahoarau** [comment]
You're right, we can just remove that line. Thanks !
